Update docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -92,10 +92,21 @@ jobs:
           echo "$RESPONSE" > /tmp/portainer-token.json
           cat /tmp/portainer-token.json
 
+      - name: Validate Token
+        run: |
+          TOKEN=$(cat /tmp/portainer-token.json | jq -r '.jwt')
+          if [ -z "$TOKEN" ]; then
+            echo "Error: Token is empty or invalid"
+            exit 1
+          else
+            echo "Token: $TOKEN"
+          fi
+
       - name: Redeploy Website Stack
         run: |
           TOKEN=$(cat /tmp/portainer-token.json | jq -r '.jwt')
-          curl -s -X POST "https://${{ secrets.PORTAINER_URL }}/api/stacks/14/deploy" \
-          -H "Authorization: Bearer $TOKEN" \
-          -H "Content-Type: application/json"
-          
+          echo "Token: $TOKEN"
+          RESPONSE=$(curl -s -X POST "https://${{ secrets.PORTAINER_URL }}/api/stacks/14/deploy" \
+            -H "Authorization: Bearer $TOKEN" \
+            -H "Content-Type: application/json")
+          echo "Redeploy Response: $RESPONSE"
